### ISSUE TITLE
What are they？

### ISSUE THREAD

**Issue by lucky33333** [V-ArkS/TDPS#21]
<img width="103" alt="屏幕快照 2020-04-10 下午5 58 41" src="https://user-images.githubusercontent.com/45202254/78997508-4bba9600-7b79-11ea-806c-96a962498bef.png">

**Comment by FRESH-W-F** [comment]
they was designed as a marker used to assist the car's image identification;
just a try；
I'll delate them if they are useless or not compliant ;
