### ISSUE TITLE
The robot cannot stay on the floor

### ISSUE THREAD

**Issue by ghost** [V-ArkS/TDPS#7]
The wbt file created cannot be used as robots cannot stay on it (even the simplest EPunk robot), maybe the floor settings are not proper, or the conducting material settings have not been changed?

**Comment by Yufeng-Diao** [comment]
We have already identified where the bug comes from. We are fixing it now.

**Comment by FRESH-W-F** [comment]
we have fixed some bugs
have a try
feedback if the problem still exists

**Comment by ghost** [comment]
Good job!
