### ISSUE TITLE
The floor cannot hold too heavy objects

### ISSUE THREAD

**Issue by ghost** [V-ArkS/TDPS#9]
The floor can hold tiny objects well, such as small robots, but for heavy object, its performance is bizarre. If the object is not that heavy, it floats on the floor
![problem1-1](https://user-images.githubusercontent.com/61625850/78669012-2d049700-790e-11ea-90f6-ee0c03933017.gif)
For heavier ones, it just sinks, 
![problem1-2](https://user-images.githubusercontent.com/61625850/78669046-3beb4980-790e-11ea-899b-1c550bda9ef6.gif)
All objects in the image have well defined boundary. Please solve this problem, as our vehicle might be heavy (like a tank!)
Maybe the road object can be used, instead of the user defined plane.
![Screenshot from 2020-04-07 20-29-47](https://user-images.githubusercontent.com/61625850/78669257-94224b80-790e-11ea-9820-a09f486fa35b.png)

**Comment by ghost** [comment]
@FRESH-W-F 
@Aragami1970

**Comment by Yufeng-Diao** [comment]
Well, I notice this problem today. I have done some changes in the afternoon which don't work. I will try to solve this problem as soon as possible.

**Comment by hweiy** [comment]
OK Fixinnnnnnnng.......

**Comment by hweiy** [comment]
Iv uploaded a new version of the ma[, which i changed the path as suggested.
Hope it works!

**Comment by ghost** [comment]
Your hard working is appreciated, but there are still a lot of problems. First, the floor material of the road path and other places if different, which causes this problem:
![problem](https://user-images.githubusercontent.com/61625850/78751857-8cfa4c80-79a5-11ea-886c-d60709dcf63c.gif)

Secondly, as is shown in the figure, the vehicle sinks on non-road materials, it is not acceptable as our vehicle has to move on those materials.
Besides, there are unnecessary borders on both sides of the road, which will be obstacles for image processing. I think they should be removed.
In my opinion, as the road material is suitable for our project, it might be a good idea to use it directly as the base floor instead of placing it on other plane. The directional lines can be put on the road.
To avoid sinking, modifying parameters in WorldInfo->contractProperties might be helpful:
![Screenshot from 2020-04-08 14-25-01](https://user-images.githubusercontent.com/61625850/78751480-e9a93780-79a4-11ea-8013-b07c1e6a0212.png)
the result should look like this:
![ideal](https://user-images.githubusercontent.com/61625850/78751872-94b9f100-79a5-11ea-846d-1062d8e19d5a.gif)

**Comment by ghost** [comment]
In contract properties, parameters "bounce", "softERP" and "softCFM" might be related to the problem, the explanations of them can be found [here](https://www.cyberbotics.com/doc/reference/contactproperties).
After solving the problem, please make sure the problematic wbt files are removed.
Thanks!
![pooh2](https://user-images.githubusercontent.com/61625850/78752960-9dabc200-79a7-11ea-9190-c485adb4285f.png)

**Comment by Yufeng-Diao** [comment]
I have fixed the bugs for the floor. Thanks for your suggestion, that is very helpful.

**Comment by ghost** [comment]
Problem solved! Well done.
